In [1]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.metrics import mean_squared_error
from xgboost import XGBRegressor

from sklearn.model_selection import KFold
xgb.__version__

'1.6.1'

In [2]:
colleges = pd.read_csv('../../input/colleges/colleges.csv')
colleges.head()

   UNITID  ... median_earnings_10_years
0  100654  ...                  31400.0
1  100663  ...                  40300.0
2  100690  ...                  38100.0
3  100706  ...                  46600.0
4  100724  ...                  27800.0

[5 rows x 48 columns]

In [3]:
colleges.shape

(7063, 48)

In [4]:
colleges.columns

Index(['UNITID', 'school_name', 'city', 'state', 'zip', 'school_webpage',
       'latitude', 'longitude', 'admission_rate', 'sat_verbal_midrange',
       'sat_math_midrange', 'sat_writing_midrange', 'act_combined_midrange',
       'act_english_midrange', 'act_math_midrange', 'act_writing_midrange',
       'sat_total_average', 'undergrad_size', 'percent_white', 'percent_black',
       'percent_hispanic', 'percent_asian', 'percent_part_time',
       'average_cost_academic_year', 'average_cost_program_year',
       'tuition_(instate)', 'tuition_(out_of_state)', 'spend_per_student',
       'faculty_salary', 'percent_part_time_faculty', 'percent_pell_grant',
       'completion_rate', 'predominant_degree', 'highest_degree', 'ownership',
       'region', 'gender', 'carnegie_basic_classification',
       'carnegie_undergraduate', 'carnegie_size', 'religious_affiliation',
       'percent_female', 'agege24', 'faminc', 'mean_earnings_6_years',
       'median_earnings_6_years', 'mean_earnings_10_years',
       'median_earnings_10_years'],
      dtype='object')

In [5]:
colleges['admission_rate'] = pd.to_numeric(colleges['admission_rate'], errors='coerce')
colleges['undergrad_size'] = pd.to_numeric(colleges['undergrad_size'], errors='coerce')
colleges['sat_math_midrange'] = pd.to_numeric(colleges['sat_math_midrange'], errors='coerce')
colleges['sat_verbal_midrange'] = pd.to_numeric(colleges['sat_verbal_midrange'], errors='coerce')
colleges['act_writing_midrange'] = pd.to_numeric(colleges['act_writing_midrange'], errors='coerce')
colleges['act_math_midrange'] = pd.to_numeric(colleges['act_math_midrange'], errors='coerce')
colleges['act_english_midrange'] = pd.to_numeric(colleges['act_english_midrange'], errors='coerce')
colleges['act_combined_midrange'] = pd.to_numeric(colleges['act_combined_midrange'], errors='coerce')
colleges['completion_rate'] = pd.to_numeric(colleges['completion_rate'], errors='coerce') 
colleges['tuition_(instate)'] = pd.to_numeric(colleges['tuition_(instate)'], errors='coerce')
colleges['tuition_(out_of_state)'] = pd.to_numeric(colleges['tuition_(out_of_state)'], errors='coerce')
colleges['percent_white'] = pd.to_numeric(colleges['percent_white'], errors='coerce')
colleges['percent_black'] = pd.to_numeric(colleges['percent_black'], errors='coerce')
colleges['percent_hispanic'] = pd.to_numeric(colleges['percent_hispanic'], errors='coerce')
colleges['percent_asian'] = pd.to_numeric(colleges['percent_asian'], errors='coerce')
colleges['sat_total_average'] = pd.to_numeric(colleges['sat_total_average'], errors='coerce')
colleges['completion_rate'] = pd.to_numeric(colleges['completion_rate'], errors='coerce')
colleges['percent_female'] = pd.to_numeric(colleges['percent_female'], errors='coerce')
colleges['agege24'] = pd.to_numeric(colleges['agege24'], errors='coerce')
colleges['faculty_salary'] = pd.to_numeric(colleges['faculty_salary'], errors='coerce')
colleges['percent_part_time'] = pd.to_numeric(colleges['percent_part_time'], errors='coerce')
colleges['faminc'] = pd.to_numeric(colleges['faminc'], errors='coerce')
colleges['average_cost_academic_year'] = pd.to_numeric(colleges['average_cost_academic_year'], errors='coerce')
colleges['average_cost_program_year'] = pd.to_numeric(colleges['average_cost_program_year'], errors='coerce')
colleges['spend_per_student'] = pd.to_numeric(colleges['spend_per_student'], errors='coerce')
colleges['mean_earnings_6_years'] = pd.to_numeric(colleges['mean_earnings_6_years'], errors='coerce')
colleges['median_earnings_6_years'] = pd.to_numeric(colleges['median_earnings_6_years'], errors='coerce')
colleges['mean_earnings_10_years'] = pd.to_numeric(colleges['mean_earnings_10_years'], errors='coerce')
colleges['median_earnings_10_years'] = pd.to_numeric(colleges['median_earnings_10_years'], errors='coerce')
colleges['latitude'] = pd.to_numeric(colleges['latitude'], errors='coerce')
colleges['longitude'] = pd.to_numeric(colleges['longitude'], errors='coerce')

In [6]:
columns = ['undergrad_size', 'spend_per_student', 'admission_rate', 'mean_earnings_6_years', 'median_earnings_6_years', 'sat_math_midrange', 'sat_verbal_midrange', 
           'act_math_midrange', 'act_writing_midrange', 'latitude', 'longitude', 'completion_rate', 'tuition_(out_of_state)', 'tuition_(instate)', 'percent_white', 
           'percent_black', 'percent_hispanic', 'percent_asian', 'median_earnings_10_years', 'sat_total_average', 'completion_rate', 'faculty_salary', 'percent_female',
          'percent_part_time', 'agege24', 'faminc', 'average_cost_program_year', 'average_cost_academic_year']

In [7]:
target = colleges['percent_pell_grant'].values

In [9]:
errors = []
kf = KFold(n_splits=5, random_state=137, shuffle=True)
for train_index, test_index in kf.split(colleges):
    X_train, X_test = colleges.loc[train_index], colleges.loc[test_index]
    y_train, y_test = target[train_index], target[test_index]
    
    clf = XGBRegressor()
    clf.fit(X_train[columns].values, y_train)
    preds = clf.predict(X_test[columns].values)
    error = mean_squared_error(y_test, preds, squared=True)
    print("Fold mean squared error:", error)
    errors.append(error)

Fold mean squared error: 0.02256950198943614
Fold mean squared error: 0.023698754371021126
Fold mean squared error: 0.023200141325212434
Fold mean squared error: 0.021427902970917557
Fold mean squared error: 0.022227266317215784

In [10]:
1000*np.mean(errors)

22.62471339476061

In [11]:
1000*np.std(errors)

0.7846080538940352

In [13]:
XGBRegressor()

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, gamma=None,
             gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, n_estimators=100, n_jobs=None,
             num_parallel_tree=None, predictor=None, random_state=None,
             reg_alpha=None, reg_lambda=None, ...)