In [1]:
%load_ext watermark

In [2]:
%watermark

Last updated: 2023-01-09T16:25:04.606931-05:00

Python implementation: CPython
Python version       : 3.8.10
IPython version      : 7.28.0

Compiler    : GCC 9.3.0
OS          : Linux
Release     : 5.11.0-37-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 32
Architecture: 64bit

In [3]:
import numpy as np
import pandas as pd

In [4]:
%watermark --iversions

numpy : 1.22.4
pandas: 1.4.3

In [5]:
X_num_train = np.load('../input/higgs_small_roc/X_num_train.npy')
X_num_val = np.load('../input/higgs_small_roc/X_num_val.npy')
X_num_test = np.load('../input/higgs_small_roc/X_num_test.npy')

y_train = np.load('../input/higgs_small_roc/y_train.npy')
y_val = np.load('../input/higgs_small_roc/y_val.npy')
y_test = np.load('../input/higgs_small_roc/y_test.npy')

In [6]:
X_num_train.shape

(62751, 28)

In [7]:
X_num_train.size

1757028

In [8]:
trains = []
for i in range(5):
    trains.append(X_num_train)

In [9]:
X_num_train_5 = np.vstack(trains)

In [10]:
X_num_train_5.shape

(313755, 28)

In [11]:
columns = [f'Col{i}' for i in range(28)]

In [12]:
X_num_train_5 = pd.DataFrame(X_num_train_5, columns=columns)
X_num_test = pd.DataFrame(X_num_test, columns=columns)
X_num_val = pd.DataFrame(X_num_val, columns=columns)

In [13]:
y_train_5 = []
for i in range(5):
    y_train_5.append(y_train)

In [14]:
y_train_5 = np.hstack(y_train_5)

In [15]:
X_num_train_5.head()

,Col0,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,...,Col18,Col19,Col20,Col21,Col22,Col23,Col24,Col25,Col26,Col27
0,2.118879,-0.047779,0.422666,0.887075,1.190011,1.125486,0.433695,-1.338761,0.000000,0.439529,...,-0.323596,-1.553466,0.000000,0.742982,0.823960,1.211727,0.916147,0.578919,0.654138,0.825789
1,0.597891,1.086895,0.923151,0.226966,0.371219,0.797166,0.150490,-0.124122,1.086538,1.316699,...,0.799050,-1.554576,0.000000,0.847783,0.790057,0.983838,1.056745,1.567410,0.940275,0.807826
2,0.745762,-1.198036,-0.740429,1.239304,0.256762,0.490740,-0.103009,1.449852,2.173076,0.923754,...,1.765957,-1.242160,0.000000,0.803592,0.958226,1.042696,0.962325,0.753004,0.781717,0.711513
3,0.754730,1.291428,0.714523,0.850122,0.253473,0.934852,-0.733786,1.407166,2.173076,0.883717,...,1.262099,-0.825421,0.000000,2.054786,1.577448,0.999547,2.386760,1.455588,1.757753,1.538811
4,1.336332,-0.407173,1.026355,2.019245,0.558858,1.559704,-0.726854,-1.027756,0.000000,0.810315,...,0.766570,1.100229,3.101961,0.922455,0.879696,0.983609,0.971203,1.022390,1.006686,1.130976

In [16]:
X_num_train_5['target'] = y_train_5
X_num_test['target'] = y_test
X_num_val['target'] = y_val

In [17]:
X_num_train_5 = X_num_train_5.sample(frac=1).reset_index(drop=True)
X_num_train_5.head()

,Col0,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,...,Col19,Col20,Col21,Col22,Col23,Col24,Col25,Col26,Col27,target
0,1.523002,-1.532107,0.739492,2.025585,1.235693,1.689787,2.070545,-1.160806,0.000000,1.027498,...,0.124694,0.000000,3.100583,2.005690,1.053351,1.596478,0.998451,1.641360,2.789675,0
1,1.251050,-1.574962,1.320987,1.295937,-1.657368,0.875490,-1.150672,-0.457856,2.173076,0.392441,...,0.285063,3.101961,0.660593,1.220497,0.984565,0.839186,0.721742,0.869256,0.884359,1
2,0.295011,-0.920455,-0.547889,0.733393,0.485663,1.095073,0.451519,-0.420158,2.173076,1.238387,...,0.352208,0.000000,0.746436,1.260082,0.979221,1.253177,2.086932,1.287276,1.052515,0
3,0.956405,-0.030247,1.142321,2.080336,0.571457,0.584820,-0.090136,0.068903,1.086538,1.386575,...,-0.138992,3.101961,0.589818,0.930166,0.986823,0.761508,0.425220,0.857795,1.025146,1
4,0.845502,0.954435,1.112359,2.238715,0.491334,0.701895,0.793149,-1.098716,0.000000,0.935211,...,0.001503,3.101961,0.594908,0.931613,1.011076,1.152528,0.519392,0.814878,0.860559,0

In [18]:
X_num_train_5 = X_num_train_5.sample(frac=1).reset_index(drop=True)
X_num_train_5.head()

,Col0,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,...,Col19,Col20,Col21,Col22,Col23,Col24,Col25,Col26,Col27,target
0,0.768638,-0.269844,-1.061693,0.188825,-1.722559,1.069881,0.139597,-1.118674,0.000000,1.339487,...,-1.073467,0.000000,1.849097,1.172859,0.982598,0.984143,0.910316,1.031255,0.878684,1
1,0.670728,-0.044857,-0.972916,0.869588,0.846707,1.046246,0.397057,-0.511076,2.173076,0.807923,...,-1.496865,0.000000,0.980686,1.523984,1.055468,0.757332,1.696202,1.406200,1.124676,0
2,1.238605,-0.650665,-1.257559,0.930278,1.621894,0.972411,-2.331027,-0.266042,0.000000,0.710222,...,0.370520,0.000000,0.896834,0.815969,0.994167,0.611443,0.997044,1.073999,1.112131,0
3,0.720690,-0.053622,1.395338,2.073825,-1.426236,0.473334,0.241591,-1.408612,0.000000,1.072194,...,0.082520,3.101961,0.950307,0.807999,0.988641,0.777506,0.250322,0.779510,0.736355,1
4,0.950732,-1.014930,1.494103,0.503551,-0.179500,0.421393,0.072261,-0.558755,0.000000,0.567447,...,1.256160,0.000000,0.894762,0.974855,0.987765,0.818531,1.060615,0.722161,0.680082,0

In [19]:
X_num_train_5.to_csv('../input/higgs_small_roc/xgtrain_aug_5.csv', index=False)
X_num_val.to_csv('../input/higgs_small_roc/xgval_aug.csv', index=False)
X_num_test.to_csv('../input/higgs_small_roc/xgtest_aug.csv', index=False)