In [1]:
%load_ext watermark

In [2]:
%watermark

Last updated: 2023-01-09T21:29:23.742782-05:00

Python implementation: CPython
Python version       : 3.8.10
IPython version      : 7.28.0

Compiler    : GCC 9.3.0
OS          : Linux
Release     : 5.11.0-37-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 32
Architecture: 64bit

In [3]:
import numpy as np
import pandas as pd

In [4]:
%watermark --iversions

pandas: 1.4.3
numpy : 1.22.4

In [5]:
X_num_train = np.load('../input/higgs_small_roc/X_num_train.npy')
X_num_val = np.load('../input/higgs_small_roc/X_num_val.npy')
X_num_test = np.load('../input/higgs_small_roc/X_num_test.npy')

y_train = np.load('../input/higgs_small_roc/y_train.npy')
y_val = np.load('../input/higgs_small_roc/y_val.npy')
y_test = np.load('../input/higgs_small_roc/y_test.npy')

In [6]:
X_num_train.shape

(62751, 28)

In [7]:
X_num_train.size

1757028

In [8]:
trains = []
for i in range(25):
    trains.append(X_num_train)

In [9]:
X_num_train_25 = np.vstack(trains)

In [10]:
X_num_train_25.shape

(1568775, 28)

In [11]:
columns = [f'Col{i}' for i in range(28)]

In [12]:
X_num_train_25 = pd.DataFrame(X_num_train_25, columns=columns)
X_num_test = pd.DataFrame(X_num_test, columns=columns)
X_num_val = pd.DataFrame(X_num_val, columns=columns)

In [13]:
y_train_25 = []
for i in range(25):
    y_train_25.append(y_train)

In [14]:
y_train_25 = np.hstack(y_train_25)

In [15]:
X_num_train_25.head()

,Col0,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,...,Col18,Col19,Col20,Col21,Col22,Col23,Col24,Col25,Col26,Col27
0,2.118879,-0.047779,0.422666,0.887075,1.190011,1.125486,0.433695,-1.338761,0.000000,0.439529,...,-0.323596,-1.553466,0.000000,0.742982,0.823960,1.211727,0.916147,0.578919,0.654138,0.825789
1,0.597891,1.086895,0.923151,0.226966,0.371219,0.797166,0.150490,-0.124122,1.086538,1.316699,...,0.799050,-1.554576,0.000000,0.847783,0.790057,0.983838,1.056745,1.567410,0.940275,0.807826
2,0.745762,-1.198036,-0.740429,1.239304,0.256762,0.490740,-0.103009,1.449852,2.173076,0.923754,...,1.765957,-1.242160,0.000000,0.803592,0.958226,1.042696,0.962325,0.753004,0.781717,0.711513
3,0.754730,1.291428,0.714523,0.850122,0.253473,0.934852,-0.733786,1.407166,2.173076,0.883717,...,1.262099,-0.825421,0.000000,2.054786,1.577448,0.999547,2.386760,1.455588,1.757753,1.538811
4,1.336332,-0.407173,1.026355,2.019245,0.558858,1.559704,-0.726854,-1.027756,0.000000,0.810315,...,0.766570,1.100229,3.101961,0.922455,0.879696,0.983609,0.971203,1.022390,1.006686,1.130976

In [16]:
X_num_train_25['target'] = y_train_25
X_num_test['target'] = y_test
X_num_val['target'] = y_val

In [17]:
X_num_train_25 = X_num_train_25.sample(frac=1).reset_index(drop=True)
X_num_train_25.head()

,Col0,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,...,Col19,Col20,Col21,Col22,Col23,Col24,Col25,Col26,Col27,target
0,0.767540,0.782043,-1.544423,0.755223,0.748487,0.994763,0.694126,0.800124,2.173076,1.148240,...,0.328901,0.000000,0.802404,0.681497,0.990529,0.772788,0.693286,0.889651,0.792664,1
1,0.336371,-0.712999,-1.387397,1.181558,1.143324,1.421561,0.166333,0.668737,2.173076,1.328911,...,-1.212750,0.000000,0.863306,0.935147,0.990368,0.905348,2.159123,1.224469,1.032748,0
2,0.718494,0.056436,0.912609,1.104716,-1.615365,0.673496,-0.891232,-0.233888,0.000000,0.797850,...,1.556367,3.101961,0.837069,1.016193,0.987886,0.520122,0.695340,0.838245,0.808430,1
3,1.090917,2.140729,-0.797579,0.848758,-1.391321,0.822816,0.842660,0.583918,2.173076,0.867475,...,1.263928,0.000000,0.316132,0.817727,0.997328,1.195801,0.595709,0.874871,0.751782,1
4,0.618571,0.770355,0.971424,1.698111,0.289020,2.264805,-0.462463,-1.644776,0.000000,3.050516,...,-1.229952,0.000000,0.930551,1.717185,0.987070,2.036201,0.959578,1.790236,2.065718,1

In [18]:
X_num_train_25 = X_num_train_25.sample(frac=1).reset_index(drop=True)
X_num_train_25.head()

,Col0,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,...,Col19,Col20,Col21,Col22,Col23,Col24,Col25,Col26,Col27,target
0,0.429888,0.377846,0.608545,1.887684,-0.708886,1.274714,0.082164,0.162038,0.000000,1.212703,...,1.380460,3.101961,0.906202,1.204536,1.156882,0.725335,0.905671,0.961735,0.884222,1
1,0.890156,-0.285427,-0.064050,1.874902,-0.006876,0.754477,-0.921929,-1.229549,0.000000,0.813085,...,-1.723824,3.101961,0.895163,0.860857,0.980674,1.161862,0.558849,0.920388,0.897926,1
2,2.343798,-0.446132,-1.505582,0.463091,0.773718,1.119715,0.354477,-1.089292,1.086538,0.651551,...,0.622450,0.000000,0.806329,1.230292,1.277773,1.092877,1.998482,1.448136,1.210755,0
3,1.037296,-1.025643,1.348730,0.479062,1.039815,0.629067,-1.245735,-0.334784,0.000000,0.537482,...,0.515907,0.000000,0.854030,0.804955,0.973354,0.610136,0.424085,0.503480,0.580497,0
4,1.773724,-0.112061,1.582881,0.839803,0.810970,1.184390,0.514894,0.075556,2.173076,1.476974,...,0.469294,0.000000,1.109953,1.013873,1.082963,0.955563,2.110279,1.244972,1.160749,0

In [19]:
X_num_train_25.to_csv('../input/higgs_small_roc/xgtrain_aug_25.csv', index=False)